package com.example.mockmate.service;

import com.example.mockmate.model.ATSReport;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.xwpf.usermodel.*;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.*;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.math.BigInteger;
import java.util.List;
import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
public class ATSDownloadService {

    private final ATSAnalyzerService atsAnalyzerService;

    /**
     * Generates an improved DOCX resume by applying AI-rewritten bullets
     * and the tailored summary from the stored ATSReport.
     */
    public ResponseEntity<byte[]> generateImprovedDocx(String reportId) {

        Optional<ATSReport> maybeReport = atsAnalyzerService.getReport(reportId);
        if (maybeReport.isEmpty()) {
            return ResponseEntity.notFound().build();
        }

        ATSReport report = maybeReport.get();

        try {
            byte[] docxBytes = buildDocx(report);
            String safeName  = sanitize(report.getResumeFileName());

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION,
                            "attachment; filename=\"improved_" + safeName + ".docx\"")
                    .contentType(MediaType.parseMediaType(
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document"))
                    .body(docxBytes);

        } catch (Exception e) {
            log.error("[ATSDownload] Failed to generate DOCX for reportId={}", reportId, e);
            return ResponseEntity.internalServerError().build();
        }
    }

    // ── DOCX builder ──────────────────────────────────────────────────────────────
    private byte[] buildDocx(ATSReport report) throws Exception {
        try (XWPFDocument doc = new XWPFDocument();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            // ── Title ─────────────────────────────────────────────────────────────
            addStyledParagraph(doc, "Improved Resume", 22, true, "1F1F2E", ParagraphAlignment.CENTER);
            addEmptyLine(doc);

            // ── Tailored Summary ──────────────────────────────────────────────────
            if (report.getTailoredSummary() != null && !report.getTailoredSummary().isBlank()) {
                addSectionHeading(doc, "Professional Summary");
                addBodyParagraph(doc, report.getTailoredSummary());
                addEmptyLine(doc);
            }

            // ── AI-Rewritten Bullet Points ────────────────────────────────────────
            List<ATSReport.BulletRewrite> rewrites = report.getBulletRewrites();
            if (rewrites != null && !rewrites.isEmpty()) {
                addSectionHeading(doc, "Improved Experience Bullets");
                for (ATSReport.BulletRewrite rewrite : rewrites) {
                    addBulletParagraph(doc, rewrite.getRewritten());
                }
                addEmptyLine(doc);
            }

            // ── Matched Keywords ──────────────────────────────────────────────────
            List<String> matched = report.getMatchedKeywords();
            if (matched != null && !matched.isEmpty()) {
                addSectionHeading(doc, "Key Skills (ATS Optimized)");
                addBodyParagraph(doc, String.join("  ·  ", matched));
                addEmptyLine(doc);
            }

            // ── Missing Keywords (add these) ──────────────────────────────────────
            List<String> missing = report.getMissingKeywords();
            if (missing != null && !missing.isEmpty()) {
                addSectionHeading(doc, "Keywords to Add");
                addBodyParagraph(doc, "Consider weaving these naturally into your experience: "
                        + String.join(", ", missing));
                addEmptyLine(doc);
            }

            // ── Footer note ───────────────────────────────────────────────────────
            addStyledParagraph(doc,
                    "Generated by MockMate ATS Resume Checker · Score: " + report.getFinalScore() + "/100",
                    8, false, "999999", ParagraphAlignment.CENTER);

            doc.write(out);
            return out.toByteArray();
        }
    }

    // ── Styling helpers ───────────────────────────────────────────────────────────

    private void addSectionHeading(XWPFDocument doc, String text) {
        XWPFParagraph para = doc.createParagraph();
        para.setSpacingBefore(200);
        XWPFRun run = para.createRun();
        run.setText(text.toUpperCase());
        run.setBold(true);
        run.setFontSize(11);
        run.setColor("6B46C1");
        run.setFontFamily("Calibri");
        // underline as separator
        run.setUnderline(UnderlinePatterns.SINGLE);
    }

    private void addBodyParagraph(XWPFDocument doc, String text) {
        XWPFParagraph para = doc.createParagraph();
        para.setSpacingBefore(80);
        XWPFRun run = para.createRun();
        run.setText(text);
        run.setFontSize(11);
        run.setColor("1F1F2E");
        run.setFontFamily("Calibri");
    }

    private void addBulletParagraph(XWPFDocument doc, String text) {
        XWPFParagraph para = doc.createParagraph();
        para.setIndentationLeft(360);
        para.setSpacingBefore(60);
        XWPFRun run = para.createRun();
        // Using Unicode bullet character — no numbering XML needed
        run.setText("• " + text);
        run.setFontSize(11);
        run.setColor("1F1F2E");
        run.setFontFamily("Calibri");
    }

    private void addStyledParagraph(XWPFDocument doc, String text,
                                     int fontSize, boolean bold,
                                     String hexColor, ParagraphAlignment align) {
        XWPFParagraph para = doc.createParagraph();
        para.setAlignment(align);
        XWPFRun run = para.createRun();
        run.setText(text);
        run.setBold(bold);
        run.setFontSize(fontSize);
        run.setColor(hexColor);
        run.setFontFamily("Calibri");
    }

    private void addEmptyLine(XWPFDocument doc) {
        XWPFParagraph para = doc.createParagraph();
        para.createRun().setText("");
    }

    private String sanitize(String fileName) {
        if (fileName == null || fileName.isBlank()) return "resume";
        String name = fileName.replaceAll("\\.(pdf|docx)$", "");
        return name.replaceAll("[^a-zA-Z0-9_\\-]", "_");
    }
}
